### Word Embedding Techniques using Embedding Layer in Keras

In [ ]:
### Libraries USed Tensorflow> 2.0  and keras

In [ ]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 511.7 MB 6.2 kB/s 
     |████████████████████████████████| 1.6 MB 51.8 MB/s 
     |████████████████████████████████| 5.8 MB 18.4 MB/s 
     |████████████████████████████████| 438 kB 58.8 MB/s 
  Attempting uninstall: tensorflow-estimator
    Found existing installation: tensorflow-estimator 2.8.0
    Uninstalling tensorflow-estimator-2.8.0:
      Successfully uninstalled tensorflow-estimator-2.8.0
  Attempting uninstall: tensorboard
    Found existing installation: tensorboard 2.8.0
    Uninstalling tensorboard-2.8.0:
      Successfully uninstalled tensorboard-2.8.0
  Attempting uninstall: keras
    Found existing installation: keras 2.8.0
    Uninstalling keras-2.8.0:
      Successfully uninstalled keras-2.8.0
  Attempting uninstall: gast
    Found existing installation: gast 0.5.3
    Uninstalling gast-0.5.3:
      Successfully uninstalled gast-0.

In [2]:
import tensorflow as tf
print(tf.__version__)

2.18.0


In [3]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [4]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [5]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [6]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [7]:
onehot_repr=[one_hot(words,voc_size)for words in sent]
print(onehot_repr)

[[148, 166, 13, 268], [148, 166, 13, 460], [148, 299, 13, 414], [187, 475, 222, 123, 454], [187, 475, 222, 123, 69], [396, 148, 289, 13, 105], [316, 172, 333, 123]]


### Word Embedding Represntation

In [8]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 148 166  13 268]
 [  0   0   0   0 148 166  13 460]
 [  0   0   0   0 148 299  13 414]
 [  0   0   0 187 475 222 123 454]
 [  0   0   0 187 475 222 123  69]
 [  0   0   0 396 148 289  13 105]
 [  0   0   0   0 316 172 333 123]]


In [11]:
## 10 feature dimesnions
dim=10

In [12]:
vocab_size = 10000
embedding_dim = 100
max_length = 20  # same length as padded embedded_docs

model = Sequential()
model.add(Embedding(voc_size,10))
model.compile(optimizer='adam', loss='mse')
model(np.zeros((1, 8), dtype='int32'))

<tf.Tensor: shape=(1, 8, 10), dtype=float32, numpy=
array([[[-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],
        [-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],
        [-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],
        [-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],
        [-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],
        [-0.0248836 , -0.04694209,  0.00058324,  0.04060883,
          0.04776299, -0.03767377, -0.03574016, -0.02884264,
         -0.04277113, -0.04495829],


In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ (1, 8, 10)             │         5,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 148, 166,  13, 268], dtype=int32)

In [15]:
embedded_docs = np.array(embedded_docs)

In [17]:
print(model.predict(embedded_docs))

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 205ms/step
[[[-2.4883604e-02 -4.6942092e-02  5.8324262e-04  4.0608834e-02
    4.7762994e-02 -3.7673771e-02 -3.5740159e-02 -2.8842641e-02
   -4.2771127e-02 -4.4958293e-02]
  [-2.4883604e-02 -4.6942092e-02  5.8324262e-04  4.0608834e-02
    4.7762994e-02 -3.7673771e-02 -3.5740159e-02 -2.8842641e-02
   -4.2771127e-02 -4.4958293e-02]
  [-2.4883604e-02 -4.6942092e-02  5.8324262e-04  4.0608834e-02
    4.7762994e-02 -3.7673771e-02 -3.5740159e-02 -2.8842641e-02
   -4.2771127e-02 -4.4958293e-02]
  [-2.4883604e-02 -4.6942092e-02  5.8324262e-04  4.0608834e-02
    4.7762994e-02 -3.7673771e-02 -3.5740159e-02 -2.8842641e-02
   -4.2771127e-02 -4.4958293e-02]
  [-1.1199005e-03 -5.7290196e-03 -3.2866288e-02 -1.5660465e-02
    1.0214530e-02 -2.8924262e-02 -2.1482253e-02  3.8603555e-02
    3.5426866e-02 -5.8953650e-03]
  [ 2.6777733e-02  4.0938746e-02  1.0759901e-02 -7.4070469e-03
    2.0322096e-02 -1.2835216e-02  8.1458688e-03 -1.0719836e-02
    4.9760826e-03 -3.1268194e-02]
 

In [49]:
embedded_docs[0]

array([  0,   0,   0,   0,  41,   3,   3, 247], dtype=int32)

In [50]:
print(model.predict(embedded_docs)[0])

ValueError: Exception encountered when calling Sequential.call().

Cannot take the length of shape with unknown rank.

Arguments received by Sequential.call():
  • inputs=tf.Tensor(shape=<unknown>, dtype=int32)
  • training=False
  • mask=None

In [18]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]

In [52]:
# Get the embedding layer
embedding_layer = model.layers[0]

# Call it directly
embedded_vectors = embedding_layer(embedded_docs)
print(embedded_vectors.shape)


(7, 8, 100)


In [19]:
one_repro=[one_hot(words,vocab_size)for words in sent]
print(one_repro)

[[2394, 3379, 2602, 3249, 1806, 7535], [1149, 7337, 2602, 5811, 582, 1908], [2752, 3437, 7518, 4538], [2394, 5541, 2602, 2408, 2394, 9230], [7495, 7277, 6373, 2602, 5811, 582, 1908], [8951, 2602, 5811, 582, 1688, 9922]]


In [20]:
embedded=pad_sequences(one_repro,padding='pre',maxlen=8)
print(embedded)

[[   0    0 2394 3379 2602 3249 1806 7535]
 [   0    0 1149 7337 2602 5811  582 1908]
 [   0    0    0    0 2752 3437 7518 4538]
 [   0    0 2394 5541 2602 2408 2394 9230]
 [   0 7495 7277 6373 2602 5811  582 1908]
 [   0    0 8951 2602 5811  582 1688 9922]]


In [21]:
model=Sequential()
model.add(Embedding(vocab_size,10,input_length=8))
model.compile('adam','mse')
model(np.zeros((1,8),dtype='int32'))

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/embedding.py:90: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


<tf.Tensor: shape=(1, 8, 10), dtype=float32, numpy=
array([[[ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],
        [ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],
        [ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],
        [ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],
        [ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],
        [ 0.02388083,  0.00529528,  0.00647851,  0.04334842,
          0.04315049,  0.03619672,  0.0009652 , -0.02675526,
          0.01014942, -0.04123814],


In [22]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_1 (Embedding)         │ (1, 8, 10)             │       100,000 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 100,000 (390.62 KB)

 Trainable params: 100,000 (390.62 KB)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.predict(embedded)

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 108ms/step


array([[[ 2.38808282e-02,  5.29527664e-03,  6.47851080e-03,
          4.33484204e-02,  4.31504883e-02,  3.61967199e-02,
          9.65200365e-04, -2.67552622e-02,  1.01494193e-02,
         -4.12381403e-02],
        [ 2.38808282e-02,  5.29527664e-03,  6.47851080e-03,
          4.33484204e-02,  4.31504883e-02,  3.61967199e-02,
          9.65200365e-04, -2.67552622e-02,  1.01494193e-02,
         -4.12381403e-02],
        [ 1.07763782e-02,  5.30076027e-03, -5.08020073e-03,
         -2.82939672e-02, -4.06637304e-02, -2.77838949e-02,
          6.87192753e-03,  4.76192497e-02, -1.97592378e-02,
          1.50390528e-02],
        [ 3.63874771e-02, -3.71760502e-02, -1.71315446e-02,
          9.59400088e-03, -1.81690231e-02,  3.60523947e-02,
         -3.30837965e-02, -8.16956162e-05,  4.64508869e-02,
          5.44775650e-03],
        [ 1.68799423e-02, -4.35194969e-02,  1.57631151e-02,
          2.53626145e-02, -1.75632127e-02,  4.76381816e-02,
          1.38882883e-02, -2.35475898e-02,  3.310415